name: Build Komari Agent MIPSLE
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Official Repo
      uses: actions/checkout@v4
      with:
        repository: 'komari-monitor/komari-agent'
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Compile for MIPSLE (mipsel_24kc)
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -trimpath -ldflags="-s -w" -o komari-agent-mipsle
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: komari-agent-mipsle
        path: komari-agent-mipsle
